### PR TITLE
Amarachi

### PR DESCRIPTION
**Pull request by alisiobia**
Created a draft Landing Page

### CODE REVIEW

**Comment by alisiobia** [comment]
Created a draft landing page and made it responsive

**Comment by alisiobia** [comment]
updated index.html and added the login.html

**Comment by alisiobia** [comment]
requested against dev, thanks

**Comment by alisiobia** [comment]
https://amarachi--wavework.netlify.app/

**Review by ChijiokeFLW — APPROVED** [review]

**Pull request merged**
